apiVersion: 1

policies:
  - orgId: 1
    receiver: slack-alertas
    group_by: ['alertname']
    routes:
      - receiver: slack-alertas
        matchers:
          - severity = critical
        group_wait: 5s
        group_interval: 1m
        repeat_interval: 1m